# Generated by Django 2.1.7 on 2019-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField(max_length=50)),
                ('y', models.IntegerField(max_length=50)),
                ('z', models.IntegerField(max_length=50)),
                ('timestamp', models.IntegerField(max_length=50)),
                ('mocked', models.IntegerField(max_length=50)),
                ('longitude', models.IntegerField(max_length=50)),
                ('latitude', models.IntegerField(max_length=50)),
                ('speed', models.IntegerField(max_length=50)),
            ],
        ),
    ]
