# Generated by Django 2.1.7 on 2019-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='mocked',
            field=models.BooleanField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='speed',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='x',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='y',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='z',
            field=models.FloatField(max_length=50),
        ),
    ]
