# Generated by Django 2.1.7 on 2019-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_auto_20190727_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='jid',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
